---
networks:
  infra:
    external: true
    name: infra
services:
  npm:
    container_name: npm
    pull_policy: always
    healthcheck:
      interval: 10s
      retries: 12
      start_period: 20s
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:81/"]
      timeout: 5s
    image: jc21/nginx-proxy-manager:latest
    networks: [infra]
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    restart: unless-stopped
    volumes:
      - npmdata:/data
      - npmletsencrypt:/etc/letsencrypt
volumes:
  npmdata: {}
  npmletsencrypt: {}